config/routes.rb
Server::Application.routes.draw do
  resources :patients do
    resources :visits
  end

  resources :technicians do
    resources :visits
  end

  resources :visits do
    resources :patients
    resources :technicians
  end

  root :to => 'patients#index'

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :date, :diagnose, :patient_id, :patient, :symptoms, :technician_id, :technician, :address

  belongs_to :patient
  belongs_to :technician
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  # GET /visits
  # GET /visits.json
  def index
    magicParam = params[:magic]
    getSinglePatient = params[:getSinglePatient]
    sortBy = ""
    sortByParam = 3
    if params[:sortBy]
      sortByParam = Integer(params[:sortBy])
    end
    sortByDirection = "DESC"
    if params[:sortByDirection]
      sortByDirection = (Integer(params[:sortByDirection]) == 0 ? "DESC" : "ASC")
    end
    case sortByParam % 4
      when 0
        #"JMBG"
        sortBy = "patients.jmbg " + sortByDirection
      when 1
        #"Patient"
        sortBy = "patients.name " + sortByDirection
      when 2
        #"Technician"
        sortBy = "technicians.name " + sortByDirection
      when 3
        #"Date"
        sortBy = "visits.date " + sortByDirection
    end
    
    if magicParam
      @visits = Visit.joins(:patient, :technician)\
        .where('patients.jmbg LIKE ? OR patients.name LIKE ? OR visits.date LIKE ? OR technicians.name LIKE ?',\
            "%#{params[:magic]}%", "%#{params[:magic]}%", "%#{params[:magic]}%", "%#{params[:magic]}%")\
        .order(sortBy)
    else
      @visits = Visit.joins(:patient, :technician).order(sortBy)
    end

    if @visits.length == 0 and getSinglePatient == "1"
      potentialPatients = Patient.where("patients.name LIKE ?", "%#{params[:magic].gsub("*", "%")}%")
      if potentialPatients.length == 1
        @patient = potentialPatients[0]
      else
        @patient = {}
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => {:visits => @visits.to_json(:include => [:patient, :technician]), :patient => @patient} }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @visit = Visit.new
    @patients = Patient.all
    @technicians = Technician.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
    @patients = Patient.all
    @technicians = Technician.all
  end

  # POST /visits
  # POST /visits.json
  def create
    visitParams = params[:visit]
    patients = []
    if params[:patient]
      patients = Patient.where('patients.jmbg=?', "#{params[:patient][:jmbg]}")
    end

    if patients.length == 0
      puts("patients.length == 0")
      patient = Patient.new(params[:patient])
    elsif patients.length == 1
      patient = patients[0]
      puts("patients.length == 1 ")
      puts(patient[:id])
    end
    if params[:patient]
      visitParams[:patient] = patient
    end
    @visit = Visit.new(visitParams)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
    <% if @visit.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

          <ul>
            <% @visit.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :date %>
      <br/>
      <%= f.datetime_select :date %>
    </div>
    <div class="field">
      <%= f.label "Address" %>
      <br/>
      <%= f.text_area :address %>
    </div>
    <div class="field">
      <%= f.label "Vitals" %>
      <br/>
      <%= f.text_area :diagnose %>
    </div>
    <div class="field">
      <%= f.label :symptoms %>
      <br/>
      <%= f.text_area :symptoms %>
    </div>
    <div class="field">
      <%= f.label :patient %>
      <br/>
      <%= f.collection_select :patient_id ,@patients,:id,:name %>
    </div>
    <div class="field">
      <%= f.label :technician %>
      <br/>
      <%= f.collection_select :technician_id ,@technicians,:id,:name %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/visits/_visit.html.erb
<tr>
  <td>
    <%= visit.date %>
  </td>

  <td>
    <%= visit.diagnose %>
  </td>

  <td>
    <%= visit.symptoms %>
  </td>

  <td>
    <%= visit.patient.name %>
  </td>

  <td>
    <%= visit.technician.name %>
  </td>

  <td>
    <%= link_to 'Destroy Visit', [visit.patient, visit],
                :confirm => 'Are you sure?',
                :method => :delete %>
  </td>
  <td>
    <%= link_to 'Show', visit %>
  </td>
</tr>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing Visits</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Address</th>
    <th>Diagnose</th>
    <th>Symptoms</th>
    <th>Patient</th>
    <th>Technician</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visits.each do |visit| %>
  <tr>
    <td><%= visit.date %></td>
    <td><%= visit.address %></td>
    <td><%= visit.diagnose %></td>
    <td><%= visit.symptoms %></td>
    <td><%= visit.patient.name %></td>
    <td><%= visit.technician.name %></td>
    <td><%= link_to 'Show', visit %></td>
    <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
    <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visit', new_visit_path %>
<%= link_to 'Show Patients', patients_path %>
<%= link_to 'Show Technicians', technicians_path %>


<%= @additional_param %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @visit.date %>
</p>

<p>
  <b>Vitals:</b>
  <%= @visit.diagnose %>
</p>

<p>
  <b>Symptoms:</b>
  <%= @visit.symptoms %>
</p>

<h2>Patient</h2>
<table>
  <thead>
  <td>Name</td>
  <td>JMBG</td>
  <td>DOB</td>
  <td>Sex</td>
  <td></td>
  <td></td>
  </thead>
  <tbody>
  <%= render @visit.patient %>
  </tbody>
</table>

<h2>Technician</h2>
<table>
  <thead>
  <td>Name</td>
  <td>JMBG</td>
  <td>DOB</td>
  <td>Sex</td>
  <td></td>
  <td></td>
  </thead>
  <tbody>
  <%= render @visit.technician %>
  </tbody>
</table>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>