config/routes.rb
Server::Application.routes.draw do
  resources :patients do
    resources :visits
  end

  resources :technicians do
    resources :visits
  end

  resources :visits do
    resources :patients
    resources :technicians
  end

  root :to => 'patients#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :jmbg, :name, :dob, :sex

  validates :name, :presence => true
  validates :jmbg, :presence => true
  validates :dob, :presence => true

  #has_many :comments, :dependent => :destroy
  has_many :visits
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  #http_basic_authenticate_with :name => "root", :password => "root", :except => [:index, :show]

  # GET /patients
  # GET /patients.json
  def index
    magic = params[:magic]

    if magic
      #@patients = Patient.where('patients.name LIKE "%" AND patients.jmbg LIKE "%"')
      sex = false
      if params[:patient][:sex] == "true"
        sex = true
      end
      @patients = Patient.where('patients.name LIKE ? AND patients.jmbg LIKE ? AND patients.sex = ?', "%#{params[:patient][:name].gsub("*", "%")}%", "%#{params[:patient][:jmbg].gsub("*", "%")}%", sex)
    else
      @patients = Patient.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :jmbg %><br />
    <%= f.text_field :jmbg %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label "Male" %><br />
    <%= f.check_box :sex %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<tr>
  <td>
    <%= patient.name %>
  </td>

  <td>
    <%= patient.jmbg %>
  </td>

  <td>
    <%= patient.dob %>
  </td>

  <td>
    <%= patient.sex %>
  </td>

  <td>
    <%= link_to 'Destroy Patient', [patient],
                :confirm => 'Are you sure?',
                :method => :delete %>
  </td>
  <td>
    <%= link_to 'Show', patient %>
  </td>
</tr>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>JMBG</th>
    <th>DOB</th>
    <th>Sex</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patients.each do |patient| %>
  <tr>
    <td><%= patient.name %></td>
    <td><%= patient.jmbg %></td>
    <td><%= patient.dob %></td>
    <td><%= patient.sex %></td>
    <td><%= link_to 'Show', patient %></td>
    <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
    <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Patient', new_patient_path %>
<%= link_to 'Show Visits', visits_path %>
<%= link_to 'Show Technicians', technicians_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @patient.name %>
</p>

<p>
  <b>JMBG:</b>
  <%= @patient.jmbg %>
</p>

<p>
  <b>DOB:</b>
  <%= @patient.dob %>
</p>

<p>
  <b>Male:</b>
  <%= @patient.sex %>
</p>

<h2>Visits</h2>
<table>
  <thead>
  <td>Date</td>
  <td>Diagnose</td>
  <td>Symptoms</td>
  <td>Patient</td>
  <td>Technician</td>
  </thead>
  <tbody>
  <%= render @patient.visits %>
  </tbody>
</table>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>